spring:
  profiles:
    active: skillsService

---

spring:
  profiles: test
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

eureka:
  client:
    enabled: false
---

spring:
  application:
    name: skills
  cloud:
    services:
      registrationMethod: direct
  profiles: skillsService
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    leaseRenewalIntervalInSeconds: 10
    healthcheck:       
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

security:
  basic:
    enabled: false

server:
  servlet:
    contextPath: /v0


